MAX_LENGTH_SKILL_NAME = 124
MAX_LENGTH_PROJECT_NAME = 200
MAX_LENGTH_STATUS = 6

STATUS_OPEN = 'open'
STATUS_CLOSED = 'closed'
STATUS_DEFAULT = STATUS_OPEN
STATUS_CHOICES = [
    (STATUS_OPEN, 'Открыт'),
    (STATUS_CLOSED, 'Закрыт'),
]

AUTOCOMPLETE_LIMIT = 10
