# Generated by Django 5.2.4 on 2026-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.skill', verbose_name='Навыки, необходимые проекту'),
        ),
    ]
